# Generated by Django 2.1 on 2018-08-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Storage',
        ),
    ]
